# ASP.NET Core
# Build et Test. ASP.NET - Projets principaux ciblant .NET Core.
# Ajouter des étapes supplémentaires pour les tests, créer un package NuGet, déployer, et plus encore.
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main  # ou remplacez par votre branche principale

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Core $(buildConfiguration)'
